version: "3.8"

services:
  frontend:
    image: vahanp/tcwebapp-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: vahanp/tcwebapp-backend:latest
    restart: unless-stopped
    environment:
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - PORT=5174
    ports:
      - "5174:5174"
    network_mode: host
