name: Build, Push and Deploy

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: vahanp/tcwebapp
  LATEST_TAG: latest
  COMMIT_SHA_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Write .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          if [ ! -s .env ]; then
            echo "Error: .env file is empty"
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
          platforms: linux/amd64  # Add specific platform if needed

      - name: Verify Docker image
        run: |
          docker pull ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA_TAG }}
          docker inspect ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA_TAG }}
          docker run --rm ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA_TAG }} ls -la /var/www/html  # Verify frontend files
          docker run --rm ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA_TAG }} ls -la /app/backend   # Verify backend files

      - name: Deploy on remote server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 7771
          script: |
            set -e
            echo "=== Starting deployment ==="
            
            mkdir -p /home/${{ secrets.SERVER_USER }}/tcwebapp
            
            if [ ! -f /home/${{ secrets.SERVER_USER }}/tcwebapp/.env ]; then
              echo "Error: .env file missing on server"
              exit 1
            fi
            
            docker pull ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA_TAG }}
            
            docker rm -f tcwebapp || true
            
            docker run -d \
              --name tcwebapp \
              -p 80:80 \  # Changed from 8181 to match Dockerfile EXPOSE
              -p 5174:5174 \
              -v /home/${{ secrets.SERVER_USER }}/tcwebapp/.env:/app/.env \
              --restart unless-stopped \
              ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA_TAG }}
            
            echo "=== Deployment successful ==="
            docker ps -a | grep tcwebapp
            docker logs tcwebapp
